config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_name/:subject_id', to: 'search#subject', as: 'subject_search'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins, skip: [:registrations]
  devise_for :users
  get 'inicio', to: 'site/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # kaminari
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  paginates_per 5
  scope :_seach_, lambda { |params, page|
                    includes(:answers, :subject)
                      .where('lower(description) LIKE ?', "%#{params.downcase}%")
                      .page(page)
                  }
  scope :_seach_description_, lambda { |params|
    where('lower(description) LIKE ?', "%#{params.downcase}%")
  }

  scope :_seach_subject, lambda { |params_subject_id, page|
                           includes(:answers, :subject)
                             .where(subject_id: params_subject_id)
                             .page(page)
                         }

  scope :last_questions, lambda { |page|
    includes(:answers, :subject)
      .order('created_at desc')
      .page(page)
  }
end

app/models/subject.rb
class Subject < ApplicationRecord
  paginates_per 5
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: %i[edit update destroy]
  def index
    @admins = Admin.all.page(params[:page])
  end

  def edit; end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: 'Administrador cadastrado com sucesso'
    else
      render :edit
    end
  end

  def new
    @admin = Admin.new
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: 'Administrador excluido com sucesso'
    else
      render :index
    end
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: 'Administrador atualizado com sucesso'
    else
      render :edit
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index; end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : 'application'
  end
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < ApplicationController
  def question
    @answer = Answer.find(params[:answer_id])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    @questions = Question._seach_(params[:question], params[:page])
  end

  def subject
    @questions = Question._seach_subject(params[:subject_id], params[:page])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.last_questions(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object= nil, method= nil)
    if object && method 
      object.model.human_attribute_name(method)
    else
      "Informe os campos"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def msg_jumbotron
    if params[:question]
      "Resultados para \"#{params[:question]}\":"
    elsif params[:subject_id]
      "Resultados para \"#{params[:subject_name]}\":"
    else
      'Ultimas Perguntas Cadastradas'
    end
  end
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/site/search/questions.html.erb
<%= render partial: 'site/shared/questions'  %>

app/views/site/search/subject.html.erb
<%= render partial: 'site/shared/questions'  %>

app/views/site/shared/_questions.html.erb
<div class="jumbotron ml-5 mr-5">
  <h1> <%= msg_jumbotron %></h1>
  <% if user_signed_in? %>
    <p>O Usuário <strong>está </strong> logado <strong><%= current_user.email %></p>
    <% else %>
      <p>O Usuário <strong>não está</strong> logado</p>
    <%end%>
    <% if admin_signed_in? %>
      <p>O Admin <strong>está </strong> logado <strong><%= current_admin.email %></strong></p>
    <% else %>
      <p>O Admin <strong>não está</strong> logado</p>
    <%end%>
  </div>
  <% @questions.each do |question| %>
    <%= form_with url: site_answer_path,  local: false do |f|%>
      <div class="card ml-5 mr-5 mb-5">
        <div class="card-header">
          <span class="badge badge-dark mr-2">
            <%= link_to "#{question.subject.description} (#{question.subject.questions_count})", site_subject_search_path(question.subject.description,question.subject_id), class:"text-white"%>
          </span>
          <%= question.description %>
        </div>
        <div class="card-body">
          <ul>
            <% question.answers.each do |answer|%>
              <li style="list-style: none " class="mb-2">
                <%= radio_button_tag 'answer_id', answer.id %>
                <%= answer.description %>
              </li>
            <% end%>
            <li style="list-style: none " class="mt-3"><%= f.submit "Responder", class: "btn btn-light", id: "btn-answer-#{question.id}"%></li>
          </ul>
        </div>
      </div>
    <% end%>
  <% end%>
  <div class="ml-5">
    <%= paginate @questions %>
  </div>