config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_name/:subject_id', to: 'search#subject', as: 'subject_search'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins, skip: [:registrations]
  devise_for :users
  get 'inicio', to: 'site/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  paginates_per 5
  has_many :questions
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: %i[edit update destroy]
  def index
    @admins = Admin.all.page(params[:page])
  end

  def edit; end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: 'Administrador cadastrado com sucesso'
    else
      render :edit
    end
  end

  def new
    @admin = Admin.new
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: 'Administrador excluido com sucesso'
    else
      render :index
    end
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: 'Administrador atualizado com sucesso'
    else
      render :edit
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: %i[edit update destroy]
  before_action :get_subjects, only: %i[new edit]
  before_action :exists_description_by_question?, only: [:create]
  def index
    @questions =
      Question.includes(:subject).order(:description).page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão
   cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão
     atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão
     excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description, :subject_id,
                                     answers_attributes: %i[id description correct _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end

  def exists_description_by_question?
    if Question._seach_description_(params['question']['description'])
      generate_question_by_params
      get_subjects
      flash.now[:alert] = "Já existe questão com a descrição '#{params['question']['description'].strip}'"
      render :new
    end
  end

  def generate_question_by_params
    @question = Question.new(description: params['question']['description'],
                             subject_id: params['question']['subject_id'])
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: %i[edit update destroy]
  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def edit; end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto/Área cadastrado com sucesso'
    else
      render :edit
    end
  end

  def new
    @subject = Subject.new
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto/Área excluido com sucesso'
    else
      render :index
    end
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto/Área atualizado com sucesso'
    else
      render :edit
    end
  end

  private

  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index; end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object= nil, method= nil)
    if object && method 
      object.model.human_attribute_name(method)
    else
      "Informe os campos"
    end
  end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial:"admins_backoffice/subjects/shared/form", locals:{action_message: t('messages.editing', model: @subject.model_name.human)} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1 class="h3 mb-4 text-gray-800"><%= t('messages.listing', model: @subjects.model_name.human(count:2)) %></h1>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= translate_attribute(@subjects, :id) %></th>
        <th><%= translate_attribute(@subjects, :description) %></th>
        <th><%= translate_attribute(@subjects, :created_at) %></th>
        <th><%= translate_attribute(@subjects, :updated_at) %></th>
        <th scope="col ">
          <%= link_to new_admins_backoffice_subject_path, type:"button", class:"btn btn-success" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <th scope="row"><%= subject.id %></th>
          <td><%= subject.description %></td>
          <td><%=  I18n.l(subject.created_at) %></td>
          <td><%=  I18n.l(subject.updated_at) %></td>
          <td>
            <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn btn-primary btn-circle" do  %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to admins_backoffice_subject_path(subject), method: :delete, class:"btn btn-danger btn-circle", data: t('messages.confirm_with', item: subject.description.truncate(15))  do %>
              <i class="fas fa-trash"></i>
            <% end%></td>
        </tr>
      <% end%>
    </tbody>
  </table>
  <div class="text-center">
    <%= paginate @subjects %>
  </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial:"admins_backoffice/subjects/shared/form", locals: {action_message: t('messages.new', model: @subject.model_name.human) } %>